### ISSUE TITLE
Child routes default closed

### ISSUE THREAD

**Issue by AlvaroSanchezDomingo** [philipp-tailor/svelte_sidebar#456]
As far as I could test, the child routes are all open as default, is there any way that the child tree could show closed as default? 
Thanks for the library.

**Comment by philipp-tailor** [comment]
Thank you for the suggestion. I added it with 4688ba561dc7152d96bf402efd3ba9c1624a6a98, and released it with `0.1.0`.

**Comment by AlvaroSanchezDomingo** [comment]
I have tested version 0.1.1 but the collapseTree feature doesn´t seem to do anything. I just set the element collapseTree = true in the route property but does not collapse the child route. Maybe something not working in the new version related with collapse tree?
Thanks a lot for the effort.

**Comment by philipp-tailor** [comment]
@AlvaroSanchezDomingo it appears to me that the code works as I intended it, but it might be that it does not match your use-case:

If you go to https://sidebar.schneiders.space, you will see that the `Example Group` is collapsed by default, like so: 

<img width="334" alt="image" src="https://user-images.githubusercontent.com/47689073/164900829-02773927-d649-4699-af5c-9ec054531f04.png">

This is done with `collapseTree: true`, as you can see if you scroll down on that page to the `Routes` text area:

<img width="482" alt="image" src="https://user-images.githubusercontent.com/47689073/164902077-2695c265-5d4d-457b-b840-170f34ac680c.png">

However, if you visit https://sidebar.schneiders.space/another-link-group/enabled, which is the first link in that collapsed group, the group un-collapses. This implements a subjective opinion I have: Then a user visits a link, the user should see where they are in relation to the rest of the information hierarchy. This information would not be transparent to the user if the link group remained collapsed. If the navigation tree contains too many links with the current group open, the user can collapse it himself. But I get how this is opinionated in a way that might not suit everyone.

If you wanted to change this behavior, you could clone the repo, and change [this line](https://github.com/philipp-tailor/svelte_sidebar/blob/master/src/components/Sidebar/NavigationLinkGroup.svelte#L33) to be:
```
groupOpen = isGroupOpenByDefault
```
Note that this code would lead to the group being closed when a route in the group would be opened, even if the user had manually opened the group to navigate to that link.

**Comment by AlvaroSanchezDomingo** [comment]
I have re-tested it and it works fine, I must have done something wrong the first time. Thanks.
