### ISSUE TITLE
Failed to resolve entry for package "svelte_sidebar"

### ISSUE THREAD

**Issue by AlvaroSanchezDomingo** [philipp-tailor/svelte_sidebar#504]
Hello,

I am testing the latest version of the package 0.1.0. When I run the application with the new package it throw an error saying that it cant resolve svelte-sidebar. I think it could be related with the new version of package.json, there is a similar issue in the following github issue link. Any idea why this could be and how could be fixed?

https://github.com/indentjs/objectorarray/issues/3

Terminal response when I try to run my application.
*********************************************************************************************

  vite v2.9.5 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 291ms.

X [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "svelte_sidebar". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "svelte_sidebar". The package may have incorrect main/module/exports specified in its package.json.

  front-end/src/components/Sidenav.svelte?id=0:4:24:
      4 │     import Sidebar from 'svelte_sidebar' 

**********************************************************************************************************

Thank you.

**Comment by philipp-tailor** [comment]
Thank you for reporting this issue! 🙏🏼 

Indeed `package.json` referenced invalid file paths.

The issue is fixed with release `0.1.1`.

**Comment by AlvaroSanchezDomingo** [comment]
Your welcome, I have tested 0.1.1 and now run without any issue but the collapse tree feature doesnt seem to work. I have recommented in the previous closed issue in case there is something wrong with the new version.
https://github.com/philipp-tailor/svelte_sidebar/issues/456
