### ISSUE TITLE
Setup: Turn `src/Sidebar/` into proper package

### ISSUE THREAD

**Issue by philipp-tailor** [philipp-tailor/svelte_sidebar#71]
`src/Sidebar/*` is thought of as an independent, re-usable module. To truly reach that, it must be consumable to 3rd parties as NPM package or Github package.

**Comment by PiotrBaczkowski** [comment]
Hello, do you plan to do It in foresable feature? :)

**Comment by philipp-tailor** [comment]
@PiotrBaczkowski I planned to publish the code as package if there was interest by someone to consume it. If you'd like to use it, I'll have a look into publishing this weekend.

**Comment by philipp-tailor** [comment]
@PiotrBaczkowski Published [on NPM](https://www.npmjs.com/package/svelte_sidebar) with cb52a1394e437bd037d294bde5f97fa1d111279a.
